package core

import (
	"context"
	"crypto/tls"
	"fmt"
	"log"
	"net"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/msTimofeev/rospanel/internal/auth"
	"github.com/msTimofeev/rospanel/internal/hop"
	"github.com/msTimofeev/rospanel/internal/model"
)

// ConnInfo describes one client-facing protocol endpoint. Key is the stable
// identifier used to toggle the protocol; Enabled reports whether it currently
// appears in user subscriptions.
type ConnInfo struct {
	Key       string `json:"key"`
	Name      string `json:"name"`
	Transport string `json:"transport"`
	Security  string `json:"security"`
	Port      string `json:"port"`
	Note      string `json:"note"`
	Enabled   bool   `json:"enabled"`
	// Fingerprint is the protocol's uTLS fingerprint (empty for Hysteria2, which
	// has no uTLS — the UI then shows no fingerprint control for it).
	Fingerprint string `json:"fingerprint"`
}

// ConnectionsStatus is the public connection surface: where clients connect and
// how, per protocol.
type ConnectionsStatus struct {
	Host      string     `json:"host"`
	SNI       string     `json:"sni"`
	WSPath    string     `json:"ws_path"` // Trojan-WS path
	Protocols []ConnInfo `json:"protocols"`
	// Hysteria2 base port, hop range, and rotation interval (UDP port-hopping).
	HysteriaPort int    `json:"hysteria_port"`
	HopStart     int    `json:"hop_start"`
	HopEnd       int    `json:"hop_end"`
	HopInterval  string `json:"hop_interval"`
	// VLESS + gRPC + REALITY parameters (public key / shortId / service name are
	// generated by the panel and shown read-only for reference).
	RealityPort        int    `json:"reality_port"`
	RealityDest        string `json:"reality_dest"`
	RealityPublicKey   string `json:"reality_public_key"`
	RealityShortID     string `json:"reality_short_id"`
	RealityServiceName string `json:"reality_service_name"`
	RealityAntiReplay  bool   `json:"reality_anti_replay"` // REALITY maxTimeDiff > 0

	// Anti-DPI transport hardening (cross-protocol).
	TLSFragment bool `json:"tls_fragment"` // sing-box ClientHello fragmentation
	TLSMin13    bool `json:"tls_min13"`    // require TLS 1.3 on :443
	BlockQUIC   bool `json:"block_quic"`   // drop untunneled browser QUIC in client configs
}

// ConnectionsInfo reports the enabled protocols and their connection parameters,
// derived from settings.
func (m *Manager) ConnectionsInfo() (*ConnectionsStatus, error) {
	set, err := m.store.GetSettings()
	if err != nil {
		return nil, err
	}
	vlessPort := set.VLESSPort
	if vlessPort == 0 {
		vlessPort = 443
	}
	hyNote := ""
	if set.HopEnd > set.HysteriaPort {
		hyNote = fmt.Sprintf("%d–%d", set.HysteriaPort, set.HopEnd)
	}
	return &ConnectionsStatus{
		Host:               set.Host,
		SNI:                set.SNI,
		WSPath:             set.WSPath,
		HysteriaPort:       set.HysteriaPort,
		HopStart:           set.HopStart,
		HopEnd:             set.HopEnd,
		HopInterval:        set.HopInterval,
		RealityPort:        set.RealityPort,
		RealityDest:        set.RealityDest,
		RealityPublicKey:   set.RealityPublicKey,
		RealityShortID:     set.RealityShortID,
		RealityServiceName: set.RealityServiceName,
		RealityAntiReplay:  set.RealityMaxTimeDiff > 0,
		TLSFragment:        set.TLSFragment,
		TLSMin13:           set.TLSMin13,
		BlockQUIC:          set.BlockQUIC,
		Protocols: []ConnInfo{
			{
				Key:         "vless",
				Name:        model.ProtoVLESS,
				Transport:   "TCP (XTLS-Vision)",
				Security:    "TLS",
				Port:        strconv.Itoa(vlessPort),
				Note:        "",
				Enabled:     set.VLESSEnabled,
				Fingerprint: set.VLESSFP(),
			},
			{
				Key:         "reality",
				Name:        model.ProtoReality,
				Transport:   "gRPC",
				Security:    "REALITY",
				Port:        strconv.Itoa(set.RealityPort),
				Note:        set.RealityDest,
				Enabled:     set.RealityEnabled,
				Fingerprint: set.RealityFP(),
			},
			{
				Key:         "trojan",
				Name:        model.ProtoTrojan,
				Transport:   "WebSocket",
				Security:    "TLS",
				Port:        strconv.Itoa(vlessPort),
				Note:        "",
				Enabled:     set.TrojanEnabled,
				Fingerprint: set.TrojanFP(),
			},
			{
				Key:       "hysteria2",
				Name:      model.ProtoHysteria,
				Transport: "QUIC / UDP",
				Security:  "TLS (ALPN h3)",
				Port:      strconv.Itoa(set.HysteriaPort),
				Note:      hyNote,
				Enabled:   set.HysteriaEnabled,
			},
		},
	}, nil
}

// realityAntiReplayWindowMs is the REALITY maxTimeDiff applied when anti-replay is
// enabled — generous enough (60s) not to reject phones with a skewed clock.
const realityAntiReplayWindowMs = 60000

// portFree reports whether nothing is currently listening on the given port for
// the network ("udp" or "tcp"): it briefly binds and releases it. Used to
// pre-validate a port change before reconfiguring Xray. Note our own Xray holds
// the OLD port, so callers only check a port we aren't already bound to.
func portFree(network string, port int) bool {
	addr := fmt.Sprintf(":%d", port)
	if network == "udp" {
		c, err := net.ListenPacket("udp", addr)
		if err != nil {
			return false
		}
		_ = c.Close()
		return true
	}
	l, err := net.Listen("tcp", addr)
	if err != nil {
		return false
	}
	_ = l.Close()
	return true
}

// hopIntervalRe matches the port-hopping interval "min-max" (seconds).
var hopIntervalRe = regexp.MustCompile(`^\d+-\d+$`)

// wsPathRe validates a WebSocket path: a leading slash, then URL-path-safe chars.
var wsPathRe = regexp.MustCompile(`^/[A-Za-z0-9_\-./]{1,64}$`)

// ConnectionsUpdate is the full client-facing connection configuration applied in
// one shot: protocol toggles, link fingerprint, Trojan-WS path, and the Hysteria2
// base port / hop range / rotation interval.
type ConnectionsUpdate struct {
	Protocols         map[string]bool   `json:"protocols"`    // key → enabled
	Fingerprints      map[string]string `json:"fingerprints"` // key → uTLS fingerprint
	WSPath            string            `json:"ws_path"`
	HysteriaPort      int               `json:"hysteria_port"`
	HopStart          int               `json:"hop_start"`
	HopEnd            int               `json:"hop_end"`
	HopInterval       string            `json:"hop_interval"`
	RealityPort       int               `json:"reality_port"`
	RealityDest       string            `json:"reality_dest"`
	RealityAntiReplay bool              `json:"reality_anti_replay"`
	// RegenRealityKeys requests a fresh REALITY keypair / shortId / service name.
	RegenRealityKeys bool `json:"regen_reality_keys"`

	// Anti-DPI transport hardening (cross-protocol).
	TLSFragment bool `json:"tls_fragment"`
	TLSMin13    bool `json:"tls_min13"`
	BlockQUIC   bool `json:"block_quic"`
}

// realityHostRe validates a REALITY destination: a real domain (≥1 dot) with an
// alphabetic TLD of 2+ letters. This rejects typos like "www.max.ru1" (TLD "ru1"),
// bare IPs, and single labels.
var realityHostRe = regexp.MustCompile(`^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$`)

// validateRealityDestLive checks the donor domain actually serves TLS 1.3 +
// HTTP/2 on :443 — the requirements for a working REALITY camouflage. The
// syntactic check (realityHostRe) is done separately by the caller.
func validateRealityDestLive(host string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 7*time.Second)
	defer cancel()
	d := tls.Dialer{Config: &tls.Config{
		ServerName: host,
		MinVersion: tls.VersionTLS13, // handshake fails if the donor lacks TLS 1.3
		NextProtos: []string{"h2", "http/1.1"},
	}}
	conn, err := d.DialContext(ctx, "tcp", net.JoinHostPort(host, "443"))
	if err != nil {
		return invalid("донор %q недоступен по TLS 1.3 на :443 (%v)", host, err)
	}
	defer conn.Close()
	if conn.(*tls.Conn).ConnectionState().NegotiatedProtocol != "h2" {
		return invalid("донор %q не поддерживает HTTP/2 — выбери другой сайт", host)
	}
	return nil
}

// ApplyConnections validates and persists the whole connection surface, then does
// a SINGLE reconcile (and one nft hop refresh) — so a multi-field save restarts
// Xray at most once instead of once per field. The reconcile is a no-op for the
// Xray process when only link-level fields (fingerprint, interval) changed.
func (m *Manager) ApplyConnections(u ConnectionsUpdate) error {
	set, err := m.store.GetSettings()
	if err != nil {
		return err
	}
	fpOf := func(key string) string {
		if v := u.Fingerprints[key]; v != "" {
			return v
		}
		return "firefox"
	}
	vlessFp, trojanFp, realityFp := fpOf("vless"), fpOf("trojan"), fpOf("reality")
	for _, fp := range []string{vlessFp, trojanFp, realityFp} {
		if !model.ValidFingerprint(fp) {
			return invalid("неизвестный fingerprint %q", fp)
		}
	}
	// The user types the path without a leading slash; strip any they added and
	// prepend exactly one canonical "/".
	ws := "/" + strings.TrimLeft(strings.TrimSpace(u.WSPath), "/")
	if !wsPathRe.MatchString(ws) {
		return invalid("неверный путь WebSocket (начинается с «/», допустимы латиница, цифры, - _ . /)")
	}
	if u.HysteriaPort < 1 || u.HysteriaPort > 65535 {
		return invalid("порт вне диапазона 1–65535")
	}
	if u.HopStart < 1 || u.HopEnd > 65535 || u.HopStart > u.HopEnd {
		return invalid("неверный диапазон хопа")
	}
	interval := strings.TrimSpace(u.HopInterval)
	if interval == "" {
		interval = "5-10"
	}
	if !hopIntervalRe.MatchString(interval) {
		return invalid("неверный интервал (нужно «N-M», напр. 5-10)")
	}
	if u.RealityPort < 1 || u.RealityPort > 65535 {
		return invalid("порт REALITY вне диапазона 1–65535")
	}
	// A port we're about to (re)bind must be free on the host, so a typo'd or
	// colliding port is rejected up front instead of crash-looping Xray. Hysteria's
	// UDP listener is always up, so only a CHANGE needs checking; the REALITY inbound
	// exists only while enabled, so check whenever it'll be enabled on a port our
	// REALITY inbound isn't already holding.
	if u.HysteriaPort != set.HysteriaPort && !portFree("udp", u.HysteriaPort) {
		return invalid("UDP-порт %d уже занят — выберите другой", u.HysteriaPort)
	}
	realityHeld := set.RealityEnabled && set.RealityPrivateKey != "" && set.RealityPort == u.RealityPort
	if u.Protocols["reality"] && !realityHeld && !portFree("tcp", u.RealityPort) {
		return invalid("TCP-порт %d уже занят — выберите другой", u.RealityPort)
	}
	// REALITY donor SNIs: comma-separated, the first is primary (used in links).
	var dests []string
	for _, d := range strings.Split(u.RealityDest, ",") {
		if d = strings.TrimSpace(d); d != "" {
			if !realityHostRe.MatchString(d) {
				return invalid("домен маскировки REALITY %q не похож на настоящий", d)
			}
			dests = append(dests, d)
		}
	}
	if len(dests) == 0 {
		return invalid("укажи хотя бы один домен маскировки REALITY")
	}
	realityDest := strings.Join(dests, ",")
	// Live TLS probe each donor only when REALITY is on and the set changed — a
	// network check shouldn't slow unrelated saves.
	if u.Protocols["reality"] && (realityDest != set.RealityDest || !set.RealityEnabled) {
		for _, d := range dests {
			if err := validateRealityDestLive(d); err != nil {
				return err
			}
		}
	}

	for key, en := range u.Protocols {
		if err := m.store.SetProtocolEnabled(key, en); err != nil {
			return err
		}
	}
	if err := m.store.SetFingerprints(vlessFp, trojanFp, realityFp); err != nil {
		return err
	}
	if err := m.store.SetWSPath(ws); err != nil {
		return err
	}
	if err := m.store.SetHysteriaPorts(u.HysteriaPort, u.HopStart, u.HopEnd, interval); err != nil {
		return err
	}
	if err := m.store.SetRealityPorts(u.RealityPort, realityDest); err != nil {
		return err
	}
	maxTimeDiff := 0
	if u.RealityAntiReplay {
		maxTimeDiff = realityAntiReplayWindowMs
	}
	if err := m.store.SetAntiDPI(u.TLSFragment, u.TLSMin13, u.BlockQUIC, maxTimeDiff); err != nil {
		return err
	}
	// Generate REALITY material on explicit request, or lazily if it's missing
	// (e.g. enabling the protocol for the first time).
	if u.RegenRealityKeys || u.Protocols["reality"] && set.RealityPrivateKey == "" {
		if err := m.regenRealityKeys(); err != nil {
			return err
		}
	}
	// Re-apply the nftables hop redirect (best-effort; it clears its own old rule
	// first). The host firewall must allow the UDP range.
	if err := hop.Ensure(u.HopStart, u.HopEnd, u.HysteriaPort); err != nil {
		log.Printf("hop: re-apply failed: %v", err)
	}
	m.TriggerReconcile()
	return nil
}

// regenRealityKeys generates and persists a fresh REALITY keypair, shortId, and
// gRPC service name. Existing clients must re-import their links afterwards.
func (m *Manager) regenRealityKeys() error {
	priv, pub, err := auth.GenerateRealityKeys()
	if err != nil {
		return err
	}
	shortIDs, err := auth.RandomShortIDs()
	if err != nil {
		return err
	}
	svc, err := auth.RandomServiceName()
	if err != nil {
		return err
	}
	return m.store.SetRealityKeys(priv, pub, shortIDs, svc)
}
