-- Custom inbounds, their uniqueness constraints, the built-in REALITY lane's move
-- from gRPC to XHTTP, and user access groups — one migration for the whole feature.

-- ── Custom inbounds ────────────────────────────────────────────────────────────
-- Operator-defined listening endpoints, one row per (server, port).
--
-- server_id is 0 for the master and a nodes.id otherwise, matching the convention
-- traffic_daily and abuse_matches already use. An inbound belongs to exactly one
-- server rather than being a fleet-wide template with per-node toggles: a port that
-- is free on one box says nothing about the next one, and the REALITY identity, the
-- hop range and the TLS material are all per-machine facts.
--
-- The transport/security-dependent half lives in the `opts` JSON blob (see
-- model.InboundOpts) rather than in columns, because WHICH fields are meaningful
-- depends on the protocol × transport × security combination. Columns here are only
-- the things every inbound has and that the panel needs to query or sort by.
CREATE TABLE inbounds (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    server_id  INTEGER NOT NULL DEFAULT 0,
    enabled    INTEGER NOT NULL DEFAULT 1,
    sort       INTEGER NOT NULL DEFAULT 0,
    name       TEXT    NOT NULL,
    protocol   TEXT    NOT NULL,
    port       INTEGER NOT NULL,
    opts       TEXT    NOT NULL DEFAULT '{}',
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- Every read is "all inbounds of one server, in display order".
CREATE INDEX idx_inbounds_server ON inbounds(server_id, sort, id);

-- One ENABLED custom inbound per (server, port). The manager already refuses a
-- colliding port before writing, but that check is a read followed by an insert: two
-- admins saving at the same moment both pass it and both rows land. The result is a
-- config Xray cannot start — recoverable (the supervisor rolls back), but recoverable
-- is not prevented, and the failure lands on every user of that server.
--
-- Partial on `enabled` because a DISABLED inbound occupies nothing: parking a spare
-- configuration on a port that is currently in use is deliberately allowed, and only
-- switching it on has to contend for the port.
CREATE UNIQUE INDEX idx_inbounds_live_port ON inbounds(server_id, port) WHERE enabled = 1;

-- Display names are the node names a client shows, and they become Clash proxy names
-- / sing-box outbound tags. A duplicate tag makes a client reject the WHOLE profile,
-- so a collision here costs the user every other server too — worth a constraint of
-- its own rather than only an application check.
--
-- Not partial: a disabled inbound is still listed in the editor, and letting two
-- entries share a name only to fail on enable is the worse failure.
CREATE UNIQUE INDEX idx_inbounds_name ON inbounds(server_id, lower(name));

-- ── Built-in REALITY: gRPC → XHTTP, and Trojan-WS retirement ─────────────────────
-- The built-in REALITY lane moves from gRPC to XHTTP: gRPC+REALITY is the most
-- fingerprinted of the current combinations, and XHTTP is what upstream now pairs
-- with REALITY (with realityConfig set, its `auto` mode resolves to stream-one — one
-- request per connection, the smallest surface).
--
-- The gRPC service name and the XHTTP path are the same kind of secret — an
-- unguessable string the client must know — so the column is renamed rather than
-- replaced, and existing values are converted into a valid path. Installs keep their
-- established secret; only its spelling changes.
ALTER TABLE settings RENAME COLUMN reality_service_name TO reality_path;
ALTER TABLE nodes    RENAME COLUMN reality_service_name TO reality_path;

UPDATE settings SET reality_path = '/' || reality_path
 WHERE reality_path <> '' AND reality_path NOT LIKE '/%';
UPDATE nodes    SET reality_path = '/' || reality_path
 WHERE reality_path <> '' AND reality_path NOT LIKE '/%';

-- Trojan-WS is retired. It shared :443, our real certificate and our real SNI with
-- the Vision lane, so it added no detection diversity — only a weaker copy: nested
-- TLS for the whole session plus a WebSocket upgrade, where Vision stops nesting
-- after the inner handshake. Anyone who still wants a WebSocket lane can define one
-- as a custom inbound on its own port.
--
-- The columns (trojan_enabled, trojan_port, ws_path, trojan_fp, trojan_name) are left
-- in place: dropping them buys nothing, and leaving them means a rollback to the
-- previous binary still finds the schema it expects. The code simply stops reading
-- them. The toggle is forced off so a subscription regenerated by the new binary can
-- never resurrect the lane from a stale flag.
UPDATE settings SET trojan_enabled = 0;
UPDATE nodes    SET trojan_enabled = 0;

-- ── User access groups ───────────────────────────────────────────────────────────
-- Which connections a user is allowed to use.
--
-- The model is a whitelist that only ever RESTRICTS. A user in no group has access to
-- everything (the historical behaviour — this feature adds nothing to those users). A
-- user in one or more groups may use exactly the union of what those groups grant, and
-- nothing else. That "nothing else" is enforced where it counts: the user's credential
-- is not written into the Xray inbounds they aren't allowed, so a hand-crafted link
-- can't reach them — the subscription hiding a lane is a consequence, not the control.
CREATE TABLE groups (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       TEXT    NOT NULL,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

-- Names are how the operator refers to a group in the user UI; keep them unique so a
-- chip like «VIP» is unambiguous. Case-insensitive, matching the node/inbound rule.
CREATE UNIQUE INDEX idx_groups_name ON groups(lower(name));

-- Membership: user ↔ group, many-to-many. A user's row cascades away with the user.
CREATE TABLE group_members (
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id  INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

-- The reverse lookup — "which groups is this user in" — is the one the user list and
-- detail drawer do per row, so it gets its own index.
CREATE INDEX idx_group_members_user ON group_members(user_id);

-- What a group grants, as opaque tokens so built-in lanes and custom inbounds share
-- one table. A token is either:
--   builtin:<server_id>:<lane>   — a built-in lane on one server (server_id 0 = master;
--                                  lane is vless | reality | hysteria2)
--   inbound:<id>                 — a custom inbound (inbounds.id)
-- Tokens are strings, not foreign keys, precisely because they span two kinds of
-- target; dangling tokens (a deleted inbound or node) are swept in the app on delete
-- and are harmless meanwhile — they just grant access to something that isn't there.
CREATE TABLE group_grants (
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    token    TEXT    NOT NULL,
    PRIMARY KEY (group_id, token)
);
